# Generated by Django 5.1.2 on 2024-11-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
